import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

export type ColorObject = { name: string; hex: string };
export type AnimalObject = { name: string; classification: string };

@Injectable({
  providedIn: 'root',
})
export class DataService {
  public readonly fruitArray: ReadonlyArray<string> = [
    'Abiu',
    'Açaí',
    'Acerola',
    'Akebi',
    'Ackee',
    'African Cherry Orange',
    'American Mayapple',
    'Apple',
    'Apricot',
    'Araza',
    'Avocado',
    'Banana',
    'Bilberry',
    'Blackberry',
    'Blackcurrant',
    'Black sapote',
    'Blueberry',
    'Boysenberry',
    'Breadfruit',
    "Buddha's Hand (Fingered Citron)",
    'Cactus pear',
    'Canistel',
    'Cashew',
    'Cempedak',
    'Cherimoya (Custard Apple)',
    'Cherry',
    'Chico fruit',
    'Cloudberry',
    'Coco De Mer',
    'Coconut',
    'Crab apple',
    'Cranberry',
    'Currant',
    'Damson',
    'Date',
    'Dragonfruit (Pitaya)',
    'Durian',
    'Egg Fruit',
    'Elderberry',
    'Feijoa',
    'Fig',
    'Finger Lime (Caviar Lime)',
    'Goji berry',
    'Gooseberry',
    'Grape',
    'Raisin',
    'Grapefruit',
    'Grewia Asiatica (Phalsa or Falsa)',
    'Guava',
    'Hala Fruit',
    'Honeyberry',
    'Huckleberry',
    'Jabuticaba(Plinia)',
    'Jackfruit',
    'Jambul',
    'Japanese plum',
    'Jostaberry',
    'Jujube',
    'Juniper berry',
    'Kaffir Lime',
    'Kiwano (Horned Melon)',
    'Kiwifruit',
    'Kumquat',
    'Lemon',
    'Lime',
    'Loganberry',
    'Longan',
    'Loquat',
    'Lulo',
    'Lychee',
    'Magellan Barberry',
    'Mamey Apple',
    'Mamey Sapote',
    'Mango',
    'Mangosteen',
    'Marionberry',
    'Melon',
    'Cantaloupe',
    'Galia melon',
    'Honeydew',
    'Mouse melon',
    'Musk melon',
    'Watermelon',
    'Miracle fruit',
    'Momordica fruit',
    'Monstera deliciosa',
    'Mulberry',
    'Nance',
    'Nectarine',
    'Orange',
    'Blood orange',
    'Clementine',
    'Mandarine',
    'Tangerine',
    'Papaya',
    'Passionfruit',
    'Pawpaw',
    'Peach',
    'Pear',
    'Persimmon',
    'Plantain',
    'Plum',
    'Prune (Dried Plum)',
    'Pineapple',
    'Pineberry',
    'Plumcot (Pluot)',
    'Pomegranate',
    'Pomelo',
    'Purple mangosteen',
    'Quince',
    'Raspberry',
    'Salmonberry',
    'Rambutan (Mamin Chino)',
    'Redcurrant',
    'Rose apple',
    'Salal berry',
    'Salak',
    'Sapodilla',
    'Sapote',
    'Satsuma',
    'Shine Muscat or Vitis Vinifera',
    'Sloe or Hawthorn Berry',
    'Soursop',
    'Star apple',
    'Star fruit',
    'Strawberry',
    'Surinam cherry',
    'Tamarillo',
    'Tamarind',
    'Tangelo',
    'Tayberry',
    'Ugli fruit',
    'White currant',
    'White sapote',
    'Ximenia',
    'Yuzu',
  ];
  public readonly colorsArray: ReadonlyArray<ColorObject> = [
    { name: 'Indian Red', hex: '#CD5C5C' },
    { name: 'Light Coral', hex: '#F08080' },
    { name: 'Salmon', hex: '#FA8072' },
    { name: 'Dark Salmon', hex: '#E9967A' },
    { name: 'Light Salmon', hex: '#FFA07A' },
    { name: 'Crimson', hex: '#DC143C' },
    { name: 'Red', hex: '#FF0000' },
    { name: 'Fire Brick', hex: '#B22222' },
    { name: 'Dark Red', hex: '#8B0000' },
    { name: 'Pink', hex: '#FFC0CB' },
    { name: 'Light Pink', hex: '#FFB6C1' },
    { name: 'Hot Pink', hex: '#FF69B4' },
    { name: 'Deep Pink', hex: '#FF1493' },
    { name: 'Medium Violet Red', hex: '#C71585' },
    { name: 'Pale Violet Red', hex: '#DB7093' },
    { name: 'Light Salmon', hex: '#FFA07A' },
    { name: 'Coral', hex: '#FF7F50' },
    { name: 'Tomato', hex: '#FF6347' },
    { name: 'Orange Red', hex: '#FF4500' },
    { name: 'Dark Orange', hex: '#FF8C00' },
    { name: 'Orange', hex: '#FFA500' },
    { name: 'Gold', hex: '#FFD700' },
    { name: 'Yellow', hex: '#FFFF00' },
    { name: 'Light Yellow', hex: '#FFFFE0' },
    { name: 'Lemon Chiffon', hex: '#FFFACD' },
    { name: 'Light Goldenrod Yellow', hex: '#FAFAD2' },
    { name: 'Papaya Whip', hex: '#FFEFD5' },
    { name: 'Moccasin', hex: '#FFE4B5' },
    { name: 'Peach Puff', hex: '#FFDAB9' },
    { name: 'Pale Goldenrod', hex: '#EEE8AA' },
    { name: 'Khaki', hex: '#F0E68C' },
    { name: 'Dark Khaki', hex: '#BDB76B' },
    { name: 'Lavender', hex: '#E6E6FA' },
    { name: 'Thistle', hex: '#D8BFD8' },
    { name: 'Plum', hex: '#DDA0DD' },
    { name: 'Violet', hex: '#EE82EE' },
    { name: 'Orchid', hex: '#DA70D6' },
    { name: 'Fuchsia', hex: '#FF00FF' },
    { name: 'Magenta', hex: '#FF00FF' },
    { name: 'Medium Orchid', hex: '#BA55D3' },
    { name: 'Medium Purple', hex: '#9370DB' },
    { name: 'Rebecca Purple', hex: '#663399' },
    { name: 'Blue Violet', hex: '#8A2BE2' },
    { name: 'Dark Violet', hex: '#9400D3' },
    { name: 'Dark Orchid', hex: '#9932CC' },
    { name: 'Dark Magenta', hex: '#8B008B' },
    { name: 'Purple', hex: '#800080' },
    { name: 'Indigo', hex: '#4B0082' },
    { name: 'Slate Blue', hex: '#6A5ACD' },
    { name: 'Dark Slate Blue', hex: '#483D8B' },
    { name: 'Medium Slate Blue', hex: '#7B68EE' },
    { name: 'Green Yellow', hex: '#ADFF2F' },
    { name: 'Chartreuse', hex: '#7FFF00' },
    { name: 'Lawn Green', hex: '#7CFC00' },
    { name: 'Lime', hex: '#00FF00' },
    { name: 'Lime Green', hex: '#32CD32' },
    { name: 'Pale Green', hex: '#98FB98' },
    { name: 'Light Green', hex: '#90EE90' },
    { name: 'Medium Spring Green', hex: '#00FA9A' },
    { name: 'Spring Green', hex: '#00FF7F' },
    { name: 'Medium Sea Green', hex: '#3CB371' },
    { name: 'Sea Green', hex: '#2E8B57' },
    { name: 'Forest Green', hex: '#228B22' },
    { name: 'Green', hex: '#008000' },
    { name: 'Dark Green', hex: '#006400' },
    { name: 'Yellow Green', hex: '#9ACD32' },
    { name: 'Olive Drab', hex: '#6B8E23' },
    { name: 'Olive', hex: '#808000' },
    { name: 'Dark Olive Green', hex: '#556B2F' },
    { name: 'Medium Aquamarine', hex: '#66CDAA' },
    { name: 'Dark Sea Green', hex: '#8FBC8B' },
    { name: 'Light Sea Green', hex: '#20B2AA' },
    { name: 'Dark Cyan', hex: '#008B8B' },
    { name: 'Teal', hex: '#008080' },
    { name: 'Aqua', hex: '#00FFFF' },
    { name: 'Cyan', hex: '#00FFFF' },
    { name: 'Light Cyan', hex: '#E0FFFF' },
    { name: 'Pale Turquoise', hex: '#AFEEEE' },
    { name: 'Aquamarine', hex: '#7FFFD4' },
    { name: 'Turquoise', hex: '#40E0D0' },
    { name: 'Medium Turquoise', hex: '#48D1CC' },
    { name: 'Dark Turquoise', hex: '#00CED1' },
    { name: 'Cadet Blue', hex: '#5F9EA0' },
    { name: 'Steel Blue', hex: '#4682B4' },
    { name: 'Light Steel Blue', hex: '#B0C4DE' },
    { name: 'Powder Blue', hex: '#B0E0E6' },
    { name: 'Light Blue', hex: '#ADD8E6' },
    { name: 'Sky Blue', hex: '#87CEEB' },
    { name: 'Light Sky Blue', hex: '#87CEFA' },
    { name: 'Deep Sky Blue', hex: '#00BFFF' },
    { name: 'Dodger Blue', hex: '#1E90FF' },
    { name: 'Cornflower Blue', hex: '#6495ED' },
    { name: 'Medium Slate Blue', hex: '#7B68EE' },
    { name: 'Royal Blue', hex: '#4169E1' },
    { name: 'Blue', hex: '#0000FF' },
    { name: 'Medium Blue', hex: '#0000CD' },
    { name: 'Dark Blue', hex: '#00008B' },
    { name: 'Navy', hex: '#000080' },
    { name: 'Midnight Blue', hex: '#191970' },
    { name: 'Cornsilk', hex: '#FFF8DC' },
    { name: 'Blanched Almond', hex: '#FFEBCD' },
    { name: 'Bisque', hex: '#FFE4C4' },
    { name: 'Navajo White', hex: '#FFDEAD' },
    { name: 'Wheat', hex: '#F5DEB3' },
    { name: 'Burly Wood', hex: '#DEB887' },
    { name: 'Tan', hex: '#D2B48C' },
    { name: 'Rosy Brown', hex: '#BC8F8F' },
    { name: 'Sandy Brown', hex: '#F4A460' },
    { name: 'Goldenrod', hex: '#DAA520' },
    { name: 'Dark Goldenrod', hex: '#B8860B' },
    { name: 'Peru', hex: '#CD853F' },
    { name: 'Chocolate', hex: '#D2691E' },
    { name: 'Saddle Brown', hex: '#8B4513' },
    { name: 'Sienna', hex: '#A0522D' },
    { name: 'Brown', hex: '#A52A2A' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Snow', hex: '#FFFAFA' },
    { name: 'Honey Dew', hex: '#F0FFF0' },
    { name: 'Mint Cream', hex: '#F5FFFA' },
    { name: 'Azure', hex: '#F0FFFF' },
    { name: 'Alice Blue', hex: '#F0F8FF' },
    { name: 'Ghost White', hex: '#F8F8FF' },
    { name: 'White Smoke', hex: '#F5F5F5' },
    { name: 'Sea Shell', hex: '#FFF5EE' },
    { name: 'Beige', hex: '#F5F5DC' },
    { name: 'Old Lace', hex: '#FDF5E6' },
    { name: 'Floral White', hex: '#FFFAF0' },
    { name: 'Ivory', hex: '#FFFFF0' },
    { name: 'Antique White', hex: '#FAEBD7' },
    { name: 'Linen', hex: '#FAF0E6' },
    { name: 'Lavender Blush', hex: '#FFF0F5' },
    { name: 'Misty Rose', hex: '#FFE4E1' },
    { name: 'Gainsboro', hex: '#DCDCDC' },
    { name: 'Light Gray', hex: '#D3D3D3' },
    { name: 'Silver', hex: '#C0C0C0' },
    { name: 'Dark Gray', hex: '#A9A9A9' },
    { name: 'Gray', hex: '#808080' },
    { name: 'Dim Gray', hex: '#696969' },
    { name: 'Light Slate Gray', hex: '#778899' },
    { name: 'Slate Gray', hex: '#708090' },
    { name: 'Dark Slate Gray', hex: '#2F4F4F' },
    { name: 'Black', hex: '#000000' },
  ];
  public readonly animalsArray: ReadonlyArray<AnimalObject> = [
    { name: 'Dog', classification: 'Mammals' },
    { name: 'Cat', classification: 'Mammals' },
    { name: 'Orca', classification: 'Mammals' },
    { name: 'Gorilla', classification: 'Mammals' },
    { name: 'Human', classification: 'Mammals' },
    { name: 'Penguin', classification: 'Birds' },
    { name: 'Ostrich', classification: 'Birds' },
    { name: 'Pigeon', classification: 'Birds' },
    { name: 'House Fly', classification: 'Insects' },
    { name: 'Tarantula', classification: 'Insects' },
    { name: 'Mosquito', classification: 'Insects' },
    { name: 'Beatle', classification: 'Insects' },
    { name: 'Bee', classification: 'Insects' },
    { name: 'Centipede', classification: 'Insects' },
    { name: 'Shark', classification: 'Fish' },
    { name: 'Salmon', classification: 'Fish' },
    { name: 'Tuna', classification: 'Fish' },
    { name: 'Swordfish', classification: 'Fish' },
  ];

  public simulateFetchRequest<T>(data: T, delayMs: number): Observable<T> {
    return new Observable(observer => {
      setTimeout(() => {
        observer.next(data);
        observer.complete();
      }, delayMs);
    });
  }

  constructor() {}
}
